### ISSUE TITLE
Errors on Android RN40

### ISSUE THREAD

**Issue by eranbes** [underscopeio/react-native-facebook-keyframes#7]
RN40. 

When following instructions and using`react-native link react-native-facebook-keyframes`, it is adding:
 
`import com.underscope.react.keyframes.RNFacebookKeyframesPackage;` rather than:
`import com.underscope.keyframes.RNFacebookKeyframesPackage;` to MainApplication.java.

However, even when I fix that manually I am still getting errors, please find attached.
![screen shot 2017-01-28 at 20 08 50](https://cloud.githubusercontent.com/assets/342114/22399518/afc7f1ba-e595-11e6-8128-e9cc9cf6e128.png)

**Comment by jpgarcia** [comment]
Good catch! I'm trying to figure out this one #8 then I'll publish a new npm version.

**Comment by jpgarcia** [comment]
Hey @eranbes I've just published 1.0.1 including the fix. Thanks for reporting this!
