### ISSUE TITLE
DEMO works only with default json file  - Android

### ISSUE THREAD

**Issue by eranbes** [underscopeio/react-native-facebook-keyframes#8]
Managed to get it working with the DEMO - Android

However, cannot get other JSON other than the demo working (I tried Smilies too from https://facebookincubator.github.io/Keyframes/docs/sample-files)

I am getting the following error for every other json file I use.
![screen shot 2017-01-28 at 21 33 32](https://cloud.githubusercontent.com/assets/342114/22400040/9ad2df1a-e5a2-11e6-96e5-3ad4c68e8df7.png)

**Comment by jpgarcia** [comment]
This is related to https://github.com/facebookincubator/Keyframes/issues/78 as OPACITY is not supported by v1.0. I would prefer to wait till they release a new stable version to integrate with this library. 

Anyway you can fork this repo and replace the `android/libs/keyframes.jar` by the one suggested in the above issue (http://migaweb.de/keyframes-1.0_test.jar)
